// @formatter:off
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols,JSUnusedLocalSymbols
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Opens the Yearly Goals window as a standard, decorated application window
 * and hides the tray popup. On macOS the app is promoted from an accessory to
 * a regular app so that it appears in the app switcher (Cmd-Tab); on Windows
 * the standard window shows in Alt-Tab on its own. The promotion is reverted
 * once the window closes so we go back to being a tray-only app.
 */
async openYearlyGoals() : Promise<void> {
    await TAURI_INVOKE("open_yearly_goals");
},
/**
 * Opens the Weekly Planning & Reflection window and hides the tray popup.
 * Reuses the window if it is already open.
 */
async openWeeklyPlanning() : Promise<void> {
    await TAURI_INVOKE("open_weekly_planning");
},
/**
 * Opens the Mid-day Check-in window and hides the tray popup.
 * Reuses the window if it is already open.
 */
async openMiddayCheckin() : Promise<void> {
    await TAURI_INVOKE("open_midday_checkin");
},
/**
 * Called by the webview after first render to set the window to its content height and show it.
 */
async showMidday(height: number) : Promise<void> {
    await TAURI_INVOKE("show_midday", { height });
},
/**
 * Called by the webview whenever content height changes after the initial show.
 * On Windows the bottom edge is held fixed (tray at bottom); on macOS the top
 * edge is held fixed (menu bar at top).
 */
async resizeMidday(height: number) : Promise<void> {
    await TAURI_INVOKE("resize_midday", { height });
},
/**
 * Quits the application, exiting the process.
 */
async quit() : Promise<void> {
    await TAURI_INVOKE("quit");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * The unit a [`WeightEntry`] points at — the three kinds of time-spend that
 * the weekly focus bar allocates across.
 * 
 * `MainQuest` is one entry per active main quest; `SideQuests` and
 * `Distractions` are each a single pooled entry.
 */
export type Activity = 
/**
 * A specific active main quest.
 */
{ type: "MainQuest"; id: MainQuestId } | 
/**
 * The pooled side-quest budget — all side quests share one weight.
 */
{ type: "SideQuests" } | 
/**
 * The distraction budget — unplanned, non-advancing work as a whole.
 */
{ type: "Distractions" }
/**
 * Defines the fiscal calendar for the user or org.
 * All quarter/month derivations are done relative to this config.
 */
export type Calendar = { id: CalendarId; name: string; 
/**
 * 1-based: 1 = January, 2 = February, … 12 = December.
 */
quarter_start_month: number; 
/**
 * IANA timezone string, e.g. "America/New_York". Defines the timezone in
 * which quarter boundaries are observed — e.g. Q2 ends at midnight on
 * June 30th in this timezone. Stored as a String because IANA identifiers
 * are a living list that can't be enumerated statically in a way that
 * stays correct over time.
 */
timezone: string; 
/**
 * BCP 47 language tag, e.g. `"en-US"`. The frontend passes this to
 * `Intl.DateTimeFormat` for all locale-sensitive display formatting.
 * Rust-side labels (e.g. `QuarterDisplay.label`) are currently generated
 * in English; this field becomes the Rust source of truth once i18n is added.
 */
locale: string }
export type CalendarId = string
/**
 * A grouping / colour label for forward-motion work (Main Quests and side quests).
 * Carries no weight, deadline, or cascade — purely organisational.
 */
export type Concern = { id: ConcernId; name: string; 
/**
 * Hex color, e.g. "#378ADD".
 */
color: string }
export type ConcernId = string
/**
 * A global distraction label. Editing the text propagates everywhere the
 * label is referenced.
 */
export type DistractionLabel = { id: DistractionLabelId; text: string; created_at: Epoch }
export type DistractionLabelId = string
/**
 * Unix timestamp in **milliseconds** UTC.
 * 
 * Milliseconds (not seconds) so that the wire format is native to JavaScript —
 * `Date.now()` and `Intl.DateTimeFormat` both work directly without ×1000
 * conversion. Chrono's [`DateTime::timestamp_millis`] and
 * [`DateTime::from_timestamp_millis`] are the idiomatic conversion points on
 * the Rust side.
 * 
 * `#[serde(transparent)]` means the JSON wire format is a plain `number`,
 * and specta exports it as `number` in TypeScript.
 */
export type Epoch = number
/**
 * How focus is distributed across activities (main quests, side quests,
 * distractions) for a given week or period.
 * 
 * All weights should sum to 1.0. Use [`Focus::new`] to construct
 * from raw weights — it normalizes the total automatically.
 */
export type Focus = { weights: WeightEntry[] }
/**
 * The long-term intended focus allocation that takes effect at `start_at`.
 * Set during quarterly planning; stays in effect until superseded.
 * 
 * All entry weights should sum to 1.0.
 */
export type FocusTarget = { id: FocusTargetId; 
/**
 * When these weights take effect.
 */
start_at: Epoch; note: string | null; entries: WeightEntry[] }
export type FocusTargetId = string
/**
 * Whether a weekly goal was achieved.
 * 
 * `at` is when the user marked the goal — this can happen at any point
 * during the week, not only during a formal reflection session.
 */
export type GoalOutcome = { type: "Hit"; at: Epoch } | { type: "Miss"; at: Epoch }
/**
 * A single goal outcome recorded during a check-in.
 */
export type GoalOutcomeEntry = { goal_id: WeeklyGoalId; outcome: GoalOutcome }
/**
 * Full data payload for the goal tree view.
 * This is the shape of what the eventual Tauri command will return.
 */
export type GoalTreeData = { calendar: Calendar; concerns: Concern[]; current_weights: FocusTarget; main_quests: MainQuest[]; quarterly_goals: QuarterlyGoal[]; 
/**
 * Quarters to show in the scrolling strip, in chronological order.
 * Computed by the backend at invocation time (see `calendar::quarters_to_display`).
 * Typically one past quarter, the current quarter, and two or more future quarters.
 */
quarters_to_display: QuarterDisplay[] }
/**
 * A long-horizon goal on the roadmap. Carries a mandatory deadline and a
 * [`Concern`] for grouping / colour. Each active main quest gets its own
 * allocation weight in the weekly focus bar.
 */
export type MainQuest = { id: MainQuestId; concern_id: ConcernId; 
/**
 * 1-based fiscal quarter: 1–4.
 */
due_quarter: number; 
/**
 * Fiscal year — the calendar year in which the fiscal year *starts*.
 * E.g. if [`Calendar::quarter_start_month`] is 2, Q4 of fiscal year 2025
 * ends in Jan 2026, but `due_year` is still 2025.
 */
due_year: number; text: string; created_at: Epoch }
export type MainQuestId = string
/**
 * Full payload for the mid-day check-in session.
 * The backend computes all derived fields; the frontend just renders.
 */
export type MiddayCheckinData = { calendar: Calendar; 
/**
 * When this check-in was scheduled / opened.
 */
checkin_at: Epoch; 
/**
 * When the previous check-in ended (morning start-of-day or prior midday).
 * `None` on the very first check-in of the day.
 */
last_checkin_at: Epoch | null; 
/**
 * When the next check-in is scheduled.
 */
next_checkin_at: Epoch; 
/**
 * Today's planned goals, in display order.
 */
todays_goals: WeeklyGoal[]; 
/**
 * All concerns, for color/label resolution.
 */
concerns: Concern[]; 
/**
 * All active main quests, for context resolution.
 */
main_quests: MainQuest[]; 
/**
 * All quarterly goals active this week, for ⓘ detail resolution.
 */
quarterly_goals: QuarterlyGoal[]; 
/**
 * All distraction labels, for context resolution.
 */
distraction_labels: DistractionLabel[]; 
/**
 * The weekly plan this check-in falls within.
 */
weekly_plan: WeeklyPlan }
/**
 * The artifact saved when the user completes a mid-day check-in.
 */
export type MiddayCheckinResult = { 
/**
 * When this check-in was scheduled / opened.
 */
checkin_at: Epoch; 
/**
 * When the previous check-in ended. `None` on the first check-in of the day.
 */
last_checkin_at: Epoch | null; 
/**
 * Outcomes for goals the user marked. Goals not touched are omitted.
 */
goal_outcomes: GoalOutcomeEntry[]; 
/**
 * Time distribution since last check-in, one weight per today's goal plus a
 * distraction bucket. All weights sum to 1.0.
 */
time_split: MiddayTimeSplit; note: string | null }
/**
 * One entry in a [`MiddayTimeSplit`]: how much of the period's time went to
 * a specific weekly goal.
 */
export type MiddayGoalWeight = { goal_id: WeeklyGoalId; 
/**
 * 0.0–1.0.
 */
weight: number }
/**
 * Per-goal time allocation for a midday check-in.
 * 
 * Unlike [`Focus`], which allocates across [`Activity`] buckets (MainQuest /
 * SideQuests / Distractions), this records how time was actually spent at the
 * individual [`WeeklyGoal`] level. The EOD reflection can translate this to a
 * `Focus` for pre-populating the weekly actual-split bar.
 * 
 * All `goal_weights[*].weight` values plus `distraction_weight` sum to 1.0.
 */
export type MiddayTimeSplit = { goal_weights: MiddayGoalWeight[]; 
/**
 * Weight for unplanned/distraction time not attributed to any goal.
 */
distraction_weight: number }
/**
 * A quarterly goal's parent — either a specific main quest or the side-quest
 * pool (with its own concern).
 */
export type ParentGoal = 
/**
 * Serves a specific main quest; concern is derived from the main quest.
 */
{ type: "MainQuest"; id: MainQuestId } | 
/**
 * Standalone side-quest work; the concern labels it directly.
 */
{ type: "SideQuest"; concern_id: ConcernId }
/**
 * Precomputed display info for one fiscal quarter.
 * 
 * The backend computes these at command-invocation time so the frontend never needs
 * to do fiscal-calendar math. `start_at` and `end_at` form a half-open interval
 * `[start_at, end_at)` in epoch milliseconds UTC.
 */
export type QuarterDisplay = { 
/**
 * 1-based: 1–4.
 */
quarter: number; 
/**
 * Fiscal year — calendar year in which the fiscal year starts.
 */
year: number; 
/**
 * Display label, e.g. "Q2 · Apr–Jun".
 */
label: string; 
/**
 * First millisecond of this quarter (inclusive).
 */
start_at: Epoch; 
/**
 * First millisecond of the following quarter (exclusive end).
 */
end_at: Epoch }
/**
 * Quarterly goal — a chunk of work due at the end of a specific fiscal quarter,
 * or sitting in the backlog when unscheduled.
 * 
 * Waypoints are indexed by month-of-quarter: slot 0 = first month, slot 2 =
 * third. The count of `Some` slots is the goal's size (1–3 "stars"). At least
 * one slot must be `Some`.
 */
export type QuarterlyGoal = { id: QuarterlyGoalId; parent: ParentGoal; 
/**
 * 1-based fiscal quarter: 1–4. `None` = this goal is in the backlog.
 */
due_quarter: number | null; 
/**
 * Fiscal year — the calendar year in which the fiscal year starts
 * (see [`MainQuest::due_year`]). `None` = this goal is in the backlog.
 */
due_year: number | null; text: string; created_at: Epoch; 
/**
 * Monthly milestones indexed by month-of-quarter (0 = first month of the
 * quarter). Month and year are derived from the index plus `due_quarter` /
 * `due_year` — never stored on the waypoint itself. A backlogged goal's
 * `Some` slots render as stars (no derived date).
 */
waypoints: [(Waypoint | null), (Waypoint | null), (Waypoint | null)] }
export type QuarterlyGoalId = string
/**
 * A monthly milestone within a quarterly goal.
 * 
 * The target month is derived from the slot index in
 * [`QuarterlyGoal::waypoints`] plus the parent goal's quarter — it is never
 * stored here. A completed waypoint renders by `completed_at`; an incomplete
 * one renders by slot + quarter (or as a star when the goal is backlogged).
 */
export type Waypoint = { id: WaypointId; text: string; 
/**
 * `None` until the waypoint is completed.
 */
completed_at: Epoch | null }
export type WaypointId = string
/**
 * A single weekly goal, used for both past goals (reflected on) and future
 * goals (being planned). `outcome` is `None` until the user marks it.
 */
export type WeeklyGoal = { id: WeeklyGoalId; 
/**
 * The weekly plan this goal belongs to (the week it was created for).
 */
plan_id: WeeklyPlanId; created_at: Epoch; text: string; 
/**
 * `None` while unmarked. Set to `Hit` or `Miss` when the user marks it —
 * this can happen during the week or during the following week's reflection.
 */
outcome: GoalOutcome | null; goal_ref: WeeklyGoalRef }
export type WeeklyGoalId = string
/**
 * What kind of work a [`WeeklyGoal`] represents.
 */
export type WeeklyGoalRef = 
/**
 * Planned work belonging to a concern, optionally tied to a waypoint.
 */
{ type: "Planned"; concern_id: ConcernId; waypoint_id: WaypointId | null } | 
/**
 * Unplanned work; may carry one or more distraction labels.
 */
{ type: "Distraction"; label_ids: DistractionLabelId[] }
/**
 * The planning artifact for a single week: what the user intends to do.
 */
export type WeeklyPlan = { id: WeeklyPlanId; 
/**
 * First millisecond of the week being planned (inclusive).
 */
start_at: Epoch; 
/**
 * First millisecond of the following week (exclusive end).
 */
end_at: Epoch; focus: Focus }
export type WeeklyPlanId = string
/**
 * Payload submitted when the user finishes the weekly planning session.
 */
export type WeeklyPlanRequest = { type: "Plan"; focus: Focus; goals: WeeklyGoal[] } | { type: "NoPlan"; reason: string }
/**
 * The reflection artifact for a completed week.
 */
export type WeeklyReflection = { id: WeeklyReflectionId; 
/**
 * The weekly plan this reflection is about.
 */
plan_id: WeeklyPlanId; notes: string; completed_at: Epoch; 
/**
 * User-adjusted actual time split for the past week. Starts as a
 * backend estimate; the user can edit it during the reflection session.
 */
actual_split: Focus }
export type WeeklyReflectionId = string
/**
 * Full payload for the weekly planning/reflection session UI.
 * The backend computes all derived fields; the frontend just renders.
 */
export type WeeklySessionData = { calendar: Calendar; 
/**
 * The fiscal quarter the plan week falls in. Always present — the backend
 * derives it from `plan.start_at` at invocation time.
 */
current_quarter: QuarterDisplay; 
/**
 * The plan for the coming week (focus weights + new goals).
 */
plan: WeeklyPlan; 
/**
 * The plan being reflected on (previous week). `None` on the first ever
 * session. Its `focus` is used for the "planned" bar in the time-split
 * visualization alongside `reflection.actual_split`.
 */
prev_plan: WeeklyPlan | null; 
/**
 * Reflection on the previous week. `None` if there is no prior plan to
 * reflect on (e.g. first ever weekly session).
 */
reflection: WeeklyReflection | null; 
/**
 * Goals from the previous week's plan, to be marked during reflection.
 */
past_goals: WeeklyGoal[]; 
/**
 * Goals already entered for the coming week's plan.
 */
planned_goals: WeeklyGoal[]; concerns: Concern[]; 
/**
 * Active main quests, for color/label resolution in focus-bar and goal lists.
 */
main_quests: MainQuest[]; distraction_labels: DistractionLabel[]; 
/**
 * Current long-term weight period, shown as the quarterly target reminder
 * below the focus weight sliders.
 */
current_weights: FocusTarget; 
/**
 * All quarterly goals for the current planning quarter, for the context
 * display in the plan section. Includes completed goals (shown dimmed);
 * covers both main-quest and side-quest goals.
 */
current_quarter_goals: QuarterlyGoal[]; 
/**
 * Quarterly goals available for waypoint selection when entering this
 * week's goals. Includes the current quarter and any future quarters;
 * the backend excludes goals whose every waypoint is already completed.
 */
upcoming_quarterly_goals: QuarterlyGoal[] }
/**
 * One entry in a [`FocusTarget`]: how much of the week's focus budget goes to
 * a specific [`Activity`].
 */
export type WeightEntry = { activity: Activity; 
/**
 * 0.0–1.0.
 */
weight: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
