// @formatter:off
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols,JSUnusedLocalSymbols
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Opens the Yearly Goals window as a standard, decorated application window
 * and hides the tray popup. On macOS the app is promoted from an accessory to
 * a regular app so that it appears in the app switcher (Cmd-Tab); on Windows
 * the standard window shows in Alt-Tab on its own. The promotion is reverted
 * once the window closes so we go back to being a tray-only app.
 */
async openYearlyGoals() : Promise<void> {
    await TAURI_INVOKE("open_yearly_goals");
},
/**
 * Opens the Weekly Planning & Reflection window and hides the tray popup.
 * Reuses the window if it is already open.
 */
async openWeeklyPlanning() : Promise<void> {
    await TAURI_INVOKE("open_weekly_planning");
},
/**
 * Quits the application, exiting the process.
 */
async quit() : Promise<void> {
    await TAURI_INVOKE("quit");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Annual goal — due at the end of a specific fiscal quarter.
 */
export type AnnualGoal = { id: AnnualGoalId; swimlane_id: SwimlaneId; 
/**
 * 1-based fiscal quarter: 1–4.
 */
due_quarter: number; 
/**
 * Fiscal year — the calendar year in which the fiscal year *starts*.
 * E.g. if [`Calendar::quarter_start_month`] is 2, Q4 of fiscal year 2025
 * ends in Jan 2026, but `due_year` is still 2025.
 */
due_year: number; text: string; created_at: Epoch }
export type AnnualGoalId = string
/**
 * Whether a quarterly goal serves an annual goal or is a standalone side quest.
 * 
 * A side quest is intentional work that doesn't map to any annual goal —
 * not a distraction, just independently valuable. Using an enum here (rather
 * than `Option<AnnualGoalId>`) makes the intent explicit at the type level.
 */
export type AnnualGoalRef = 
/**
 * Serves a specific annual goal.
 */
{ type: "MainQuest"; id: AnnualGoalId } | 
/**
 * Standalone work — intentional but not tied to any annual goal.
 */
{ type: "SideQuest" }
/**
 * Defines the fiscal calendar for the user or org.
 * All quarter/month derivations are done relative to this config.
 */
export type Calendar = { id: CalendarId; name: string; 
/**
 * 1-based: 1 = January, 2 = February, … 12 = December.
 */
quarter_start_month: number; 
/**
 * IANA timezone string, e.g. "America/New_York". Defines the timezone in
 * which quarter boundaries are observed — e.g. Q2 ends at midnight on
 * June 30th in this timezone. Stored as a String because IANA identifiers
 * are a living list that can't be enumerated statically in a way that
 * stays correct over time.
 */
timezone: string; 
/**
 * BCP 47 language tag, e.g. `"en-US"`. The frontend passes this to
 * `Intl.DateTimeFormat` for all locale-sensitive display formatting.
 * Rust-side labels (e.g. `QuarterDisplay.label`) are currently generated
 * in English; this field becomes the Rust source of truth once i18n is added.
 */
locale: string }
export type CalendarId = string
/**
 * A global distraction label. Editing the text propagates everywhere the
 * label is referenced.
 */
export type DistractionLabel = { id: DistractionLabelId; text: string; created_at: Epoch }
export type DistractionLabelId = string
/**
 * Unix timestamp in **milliseconds** UTC.
 * 
 * Milliseconds (not seconds) so that the wire format is native to JavaScript —
 * `Date.now()` and `Intl.DateTimeFormat` both work directly without ×1000
 * conversion. Chrono's [`DateTime::timestamp_millis`] and
 * [`DateTime::from_timestamp_millis`] are the idiomatic conversion points on
 * the Rust side.
 * 
 * `#[serde(transparent)]` means the JSON wire format is a plain `number`,
 * and specta exports it as `number` in TypeScript.
 */
export type Epoch = number
/**
 * Whether a weekly goal was achieved.
 * 
 * `at` is when the user marked the goal — this can happen at any point
 * during the week, not only during a formal reflection session.
 */
export type GoalOutcome = { type: "Hit"; at: Epoch } | { type: "Miss"; at: Epoch }
/**
 * Full data payload for the goal tree view.
 * This is the shape of what the eventual Tauri command will return.
 */
export type GoalTreeData = { calendar: Calendar; swimlanes: Swimlane[]; current_weights: SwimlaneWeightPeriod; annual_goals: AnnualGoal[]; quarterly_goals: QuarterlyGoal[]; 
/**
 * Quarters to show in the scrolling strip, in chronological order.
 * Computed by the backend at invocation time (see `calendar::quarters_to_display`).
 * Typically one past quarter, the current quarter, and two or more future quarters.
 */
quarters_to_display: QuarterDisplay[] }
/**
 * Precomputed display info for one fiscal quarter.
 * 
 * The backend computes these at command-invocation time so the frontend never needs
 * to do fiscal-calendar math. `start_at` and `end_at` form a half-open interval
 * `[start_at, end_at)` in epoch milliseconds UTC.
 */
export type QuarterDisplay = { 
/**
 * 1-based: 1–4.
 */
quarter: number; 
/**
 * Fiscal year — calendar year in which the fiscal year starts.
 */
year: number; 
/**
 * Display label, e.g. "Q2 · Apr–Jun".
 */
label: string; 
/**
 * First millisecond of this quarter (inclusive).
 */
start_at: Epoch; 
/**
 * First millisecond of the following quarter (exclusive end).
 */
end_at: Epoch }
/**
 * Quarterly goal — due at the end of a specific fiscal quarter.
 */
export type QuarterlyGoal = { id: QuarterlyGoalId; swimlane_id: SwimlaneId; annual_goal: AnnualGoalRef; 
/**
 * 1-based fiscal quarter: 1–4.
 */
due_quarter: number; 
/**
 * Fiscal year — the calendar year in which the fiscal year starts
 * (see [`AnnualGoal::due_year`]).
 */
due_year: number; text: string; created_at: Epoch; waypoints: Waypoint[] }
export type QuarterlyGoalId = string
export type Swimlane = { id: SwimlaneId; name: string; 
/**
 * Hex color, e.g. "#378ADD".
 */
color: string }
export type SwimlaneId = string
/**
 * Read-only quarter context for one swimlane, shown during the planning phase
 * so the user can set weekly goals relative to their quarterly commitments.
 */
export type SwimlanePlanningContext = { swimlane_id: SwimlaneId; quarter: QuarterDisplay; 
/**
 * `None` if the swimlane has no quarterly goal for the active quarter.
 */
quarterly_goal: QuarterlyGoal | null }
export type SwimlaneWeight = { target: WeightTarget; 
/**
 * 0.0–1.0.
 */
weight: number }
export type SwimlaneWeightPeriod = { id: SwimlaneWeightPeriodId; 
/**
 * When these weights take effect.
 */
start_at: Epoch; note: string | null; entries: SwimlaneWeight[] }
export type SwimlaneWeightPeriodId = string
/**
 * How focus is distributed across swimlanes and distractions.
 * 
 * All weights should sum to 1.0. Use [`SwimlanesFocus::new`] to construct
 * from raw weights — it normalizes the total automatically.
 */
export type SwimlanesFocus = { weights: SwimlaneWeight[] }
/**
 * Waypoint — a monthly milestone within a quarterly goal.
 */
export type Waypoint = { id: WaypointId; quarterly_goal_id: QuarterlyGoalId; 
/**
 * Calendar month (not fiscal), 1-based: 1 = January … 12 = December.
 * Calendar rather than fiscal because months are already unambiguous
 * without fiscal adjustment.
 */
target_month: number; 
/**
 * Calendar year.
 */
target_year: number; text: string; 
/**
 * `None` until the waypoint is completed.
 */
completed_at: Epoch | null }
export type WaypointId = string
/**
 * A single weekly goal, used for both past goals (reflected on) and future
 * goals (being planned). `outcome` is `None` until the user marks it.
 */
export type WeeklyGoal = { id: WeeklyGoalId; 
/**
 * The weekly plan this goal belongs to (the week it was created for).
 */
plan_id: WeeklyPlanId; created_at: Epoch; text: string; 
/**
 * `None` while unmarked. Set to `Hit` or `Miss` when the user marks it —
 * this can happen during the week or during the following week's reflection.
 */
outcome: GoalOutcome | null; goal_ref: WeeklyGoalRef }
export type WeeklyGoalId = string
/**
 * What kind of work a [`WeeklyGoal`] represents.
 */
export type WeeklyGoalRef = 
/**
 * Planned work belonging to a swimlane, optionally tied to a waypoint.
 */
{ type: "Planned"; swimlane_id: SwimlaneId; waypoint_id: WaypointId | null } | 
/**
 * Unplanned work; may carry one or more distraction labels.
 */
{ type: "Distraction"; label_ids: DistractionLabelId[] }
/**
 * The planning artifact for a single week: what the user intends to do.
 */
export type WeeklyPlan = { id: WeeklyPlanId; 
/**
 * First millisecond of the week being planned (inclusive).
 */
start_at: Epoch; 
/**
 * First millisecond of the following week (exclusive end).
 */
end_at: Epoch; focus: SwimlanesFocus }
export type WeeklyPlanId = string
/**
 * The reflection artifact for a completed week.
 */
export type WeeklyReflection = { id: WeeklyReflectionId; 
/**
 * The weekly plan this reflection is about.
 */
plan_id: WeeklyPlanId; notes: string; completed_at: Epoch; 
/**
 * User-adjusted actual time split for the past week. Starts as a
 * backend estimate; the user can edit it during the reflection session.
 */
actual_split: SwimlanesFocus }
export type WeeklyReflectionId = string
/**
 * Full payload for the weekly planning/reflection session UI.
 * The backend computes all derived fields; the frontend just renders.
 */
export type WeeklySessionData = { calendar: Calendar; 
/**
 * The plan for the coming week (focus weights + new goals).
 */
plan: WeeklyPlan; 
/**
 * The plan being reflected on (previous week). `None` on the first ever
 * session. Its `focus` is used for the "planned" bar in the time-split
 * visualization alongside `reflection.actual_split`.
 */
prev_plan: WeeklyPlan | null; 
/**
 * Reflection on the previous week. `None` if there is no prior plan to
 * reflect on (e.g. first ever weekly session).
 */
reflection: WeeklyReflection | null; 
/**
 * Goals from the previous week's plan, to be marked during reflection.
 */
past_goals: WeeklyGoal[]; 
/**
 * Goals already entered for the coming week's plan.
 */
planned_goals: WeeklyGoal[]; swimlanes: Swimlane[]; distraction_labels: DistractionLabel[]; 
/**
 * Active quarter context per swimlane, for the planning section.
 */
quarter_context: SwimlanePlanningContext[]; 
/**
 * Current long-term weight period, shown as the quarterly target reminder
 * below the focus weight sliders.
 */
current_weights: SwimlaneWeightPeriod }
/**
 * What a [`SwimlaneWeight`] allocates weight toward.
 * 
 * Including `Distractions` as a first-class target lets the user budget
 * intentionally for unplanned work rather than having it silently erode
 * the swimlane allocations.
 */
export type WeightTarget = 
/**
 * A specific swimlane.
 */
{ type: "Swimlane"; id: SwimlaneId } | 
/**
 * The distraction budget — unplanned work as a whole.
 */
{ type: "Distractions" }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
